export const suffixes = [
    "K",   // thousand
    "M",   // million
    "B",   // billion
    "T",   // trillion
    "Qa",  // quadrillion
    "Qi",  // quintillion
    "Sx",  // sextillion
    "Sp",  // septillion
    "Oc",  // octillion
    "No",  // nonillion
    "Dc",   // decillion
    "UDc",  // undecillion
    "DDc",  // duodecillion
    "TDc",  // tredecillion
    "QaDc", // quattuordecillion
    "QiDc", // quindecillion
    "SxDc", // sexdecillion
    "SpDc", // septendecillion
    "OcDc", // octodecillion
    "NoDc", // novemdecillion
    "Vg",   // vigintillion
    "UVg",  // unvigintillion
    "DVg",  // duovigintillion
    "TVg",  // trevigintillion
    "QaVg", // quattuorvigintillion
    "QiVg", // quinvigintillion
    "SxVg", // sexvigintillion
    "SpVg", // septenvigintillion
    "OcVg", // octovigintillion
    "NoVg", // novemvigintillion
    "Tg",   // trigintillion
    "UTg",  // untrigintillion
    "DTg",  // duotrigintillion
    "TTg",  // tretrigintillion
    "QaTg", // quattuortrigintillion
    "QiTg", // quintrigintillion
    "SxTg", // sextrigintillion
    "SpTg", // septentrigintillion
    "OcTg", // octotrigintillion
    "NoTg", // novemtrigintillion
    "QaTg", // quattuordecillion
    "QiTg", // quindecillion
    "SxTg", // sexdecillion
    "SpTg", // septendecillion
    "OcTg", // octodecillion
    "NoTg", // novemdecillion
    "Vg",   // vigintillion
    "UVg",  // unvigintillion
    "DVg",  // duovigintillion
    "TVg",  // trevigintillion
    "QaVg", // quattuorvigintillion
    "QiVg", // quinvigintillion
    "SxVg", // sexvigintillion
    "SpVg", // septenvigintillion
    "OcVg", // octovigintillion
    "NoVg", // novemvigintillion
    "Tg",   // trigintillion
    "UTg",  // untrigintillion
    "DTg",  // duotrigintillion
    "TTg",  // tretrigintillion
    "QaTg", // quattuortrigintillion
    "QiTg", // quintrigintillion
    "SxTg", // sextrigintillion
    "SpTg", // septentrigintillion
    "OcTg", // octotrigintillion
    "NoTg", // novemtrigintillion
    "QaTg", // quattuordecillion
    "QiTg", // quindecillion
    "SxTg", // sexdecillion
    "SpTg", // septendecillion
    "OcTg", // octodecillion
    "NoTg", // novemdecillion
    "Vg",   // vigintillion
    "UVg",  // unvigintillion
    "DVg",  // duovigintillion
    "TVg",  // trevigintillion
    "QaVg", // quattuorvigintillion
    "QiVg", // quinvigintillion
    "SxVg", // sexvigintillion
    "SpVg", // septenvigintillion
    "OcVg", // octovigintillion
    "NoVg", // novemvigintillion
    "Tg",   // trigintillion
    "UTg",  // untrigintillion
    "DTg",  // duotrigintillion
    "TTg",  // tretrigintillion
    "QaTg", // quattuortrigintillion
    "QiTg", // quintrigintillion
    "SxTg", // sextrigintillion
    "SpTg", // septentrigintillion
    "OcTg", // octotrigintillion
    "NoTg", // novemtrigintillion
    "QaTg", // quattuordecillion
    "QiTg", // quindecillion
    "SxTg", // sexdecillion
    "SpTg", // septendecillion
    "OcTg", // octodecillion
    "NoTg", // novemdecillion
    "Vg",   // vigintillion
    "UVg",  // unvigintillion
    "DVg",  // duovigintillion
    "TVg",  // trevigintillion
    "QaVg", // quattuorvigintillion
    "QiVg", // quinvigintillion
    "SxVg", // sexvigintillion
    "SpVg", // septenvigintillion
    "OcVg", // octovigintillion
    "NoVg", // novemvigintillion
    "Tg",   // trigintillion
    "UTg",  // untrigintillion
    "DTg",  // duotrigintillion
    "TTg",  // tretrigintillion
    "QaTg", // quattuortrigintillion
    "QiTg", // quintrigintillion
    "SxTg", // sextrigintillion
    "SpTg", // septentrigintillion
    "OcTg", // octotrigintillion
    "NoTg", // novemtrigintillion
];